spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ccinside;MODE=MySQL;DATABASE_TO_LOWER=true;database_to_upper=false;CASE_INSENSITIVE_IDENTIFIERS=true
    username: sa
    password: ''
