version: '3.4'

services:
  mysql:
    image: 'mysql:8.0'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER=ccinside
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=ccinside_local
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ccinside

  redis:
    image: 'redis:latest'
    container_name: "ccinside-redis"
    ports:
      - "6381:6379"
    networks:
      - ccinside

networks:
  ccinside:
    driver: bridge
